services:
#  mysql:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: pass4mingming
#    ports:
#      - 3306:3306
#
#  redis:
#    image: redis
#    restart: always
#    ports:
#      - 6379:6379
#
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    ports:
#      - 5672:5672
#      - 15672:15672

  svc-user:
    container_name: svc-user
    build:
      context: "./src"
      dockerfile: "Dockerfile"
    ports:
      - 9091:9091
    volumes:
      - ./src:/opt/center/src

